# Generated by Django 5.1.1 on 2024-09-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("sensor_value", models.IntegerField()),
            ],
        ),
    ]
